apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-hwkb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0060-tenant/tkrw-pr712-0075-0060-app/devfile-sample-hwkb@sha256:c50bc5753953081a398cae81ec3633f356a90e1056bc1596fa3d8c254213255a
        name: my-nodejs
        resources: {}
status: {}
